name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: cmdr-linux-x86_64
            binary_name: cmdr
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: cmdr-macos-x86_64
            binary_name: cmdr
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: cmdr-windows-x86_64
            binary_name: cmdr.exe

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Build
      run: |
        cargo build --release --bin cmdr
        cp target/release/${{ matrix.binary_name }} ${{ matrix.artifact_name }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cmdr-linux-x86_64/cmdr-linux-x86_64
          cmdr-macos-x86_64/cmdr-macos-x86_64
          cmdr-windows-x86_64/cmdr-windows-x86_64
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 